import { describe, it, expect, beforeAll } from "vitest";
import { readFileSync } from "node:fs";
import { runCheck, SHRINK_LIMIT } from "../src/lib/runCheck.js";
import { FIXTURE_COUNT, TEAM_COUNT } from "./fixtures/meta.js";

const html = readFileSync(new URL("./fixtures/club2960.html", import.meta.url), "utf8");
const NOW = "2026-08-25T06:00:11Z";
const TODAY = "2026-08-25";

// One run of the real capture from cold. Used as the starting point for almost every
// scenario below, so it is built once and never mutated. Built in a hook rather than at
// module load so that a regression here fails tests instead of failing collection.
let first;
beforeAll(() => {
  first = runCheck({ html, previous: null, config: null, now: NOW, today: TODAY });
});

// A previous snapshot built by editing the real one, so the only differences are the
// ones the test is about.
const prevWith = (edit) => ({ ...first.snapshot, fixtures: edit(first.snapshot.fixtures) });

describe("runCheck", () => {
  it("produces a snapshot from the real capture", () => {
    const out = runCheck({ html, previous: null, config: null, now: NOW, today: TODAY });
    expect(out.snapshot.version).toBe(1);
    expect(out.snapshot.fetchedAt).toBe(NOW);
    expect(out.snapshot.fixtures).toHaveLength(FIXTURE_COUNT);
  });

  it("seeds a config covering every squad on a first run", () => {
    const out = runCheck({ html, previous: null, config: null, now: NOW, today: TODAY });
    expect(Object.keys(out.config.teams)).toHaveLength(TEAM_COUNT);
    expect(out.unknown.every((id) => id in out.config.teams)).toBe(true);
    expect(out.unknown.every((id) => out.config.teams[id].label === null)).toBe(true);
  });

  it("reports no changes when the previous snapshot is identical", () => {
    const second = runCheck({ html, previous: first.snapshot, config: first.config, now: NOW, today: TODAY });
    expect(second.changes).toEqual([]);
    expect(second.report).toBeNull();
  });

  it("treats a first-ever run as no changes, not a whole season of new fixtures", () => {
    const out = runCheck({ html, previous: null, config: null, now: NOW, today: TODAY });
    expect(out.changes).toEqual([]);
    expect(out.firstRun).toBe(true);
  });

  it("detects a change against a previous snapshot", () => {
    const previous = prevWith((fs) => fs.map((f, i) => (i === 0 ? { ...f, time: "09:00" } : f)));
    const out = runCheck({ html, previous, config: first.config, now: NOW, today: TODAY });
    expect(out.changes).toHaveLength(1);
    expect(out.changes[0].type).toBe("moved");
    expect(out.report.subject).toMatch(/1 change/);
    expect(out.firstRun).toBe(false);
  });

  it("prepends this run to the change history, newest first", () => {
    const previous = prevWith((fs) => fs.map((f, i) => (i === 0 ? { ...f, venue: "Nowhere" } : f)));
    const history = [{ checkedAt: "2026-08-24T06:00:00Z", changes: [] }];
    const out = runCheck({ html, previous, config: first.config, now: NOW, today: TODAY, history });
    expect(out.history).toHaveLength(2);
    expect(out.history[0].checkedAt).toBe(NOW);
    expect(out.history[1].checkedAt).toBe("2026-08-24T06:00:00Z");
    expect(out.history[0].changes).toEqual(out.changes);
  });

  it("leaves the history untouched on a quiet day", () => {
    const history = [{ checkedAt: "2026-08-24T06:00:00Z", changes: [] }];
    const out = runCheck({ html, previous: first.snapshot, config: first.config, now: NOW, today: TODAY, history });
    expect(out.history).toEqual(history);
  });

  it("defaults the history to empty and still records a change", () => {
    const previous = prevWith((fs) => fs.map((f, i) => (i === 0 ? { ...f, venue: "Nowhere" } : f)));
    const out = runCheck({ html, previous, config: first.config, now: NOW, today: TODAY });
    expect(out.history).toHaveLength(1);
    expect(out.history[0].checkedAt).toBe(NOW);
  });

  it("does not mutate the history it was handed", () => {
    const entry = { checkedAt: "2026-08-24T06:00:00Z", changes: [] };
    const history = Object.freeze([entry]);
    const previous = prevWith((fs) => fs.map((f, i) => (i === 0 ? { ...f, venue: "Nowhere" } : f)));
    const out = runCheck({ html, previous, config: first.config, now: NOW, today: TODAY, history });
    expect(out.history).not.toBe(history);
    expect(history).toHaveLength(1);
    expect(out.history).toHaveLength(2);
  });
});

// THE rule. Everything here must throw rather than hand back a snapshot.
describe("runCheck aborts rather than writing an empty snapshot", () => {
  const cloudfront = `<!DOCTYPE html><html><head><title>ERROR: The request could not be satisfied</title></head>
    <body><h1>403 ERROR</h1><p>Request blocked. Generated by cloudfront (CloudFront)</p></body></html>`;
  const maintenance = `<!DOCTYPE html><html><body><h1>Briefly unavailable for scheduled maintenance.
    Check back in a minute.</h1></body></html>`;
  const noBlocks = `<!DOCTYPE html><html><body><div class="fixtures-wrap"><p>No fixtures found.</p>
    </div></body></html>`;
  const truncated = html.slice(0, 400);

  for (const [name, bad] of [
    ["a blocked page", "<html>blocked</html>"],
    ["a CloudFront 403 error page", cloudfront],
    ["a WordPress maintenance page", maintenance],
    ["valid HTML with zero fixture blocks", noBlocks],
    ["a truncated response", truncated],
    ["an empty response body", ""],
    ["whitespace only", "   \n\t  "],
    ["null html", null],
    ["undefined html", undefined],
  ]) {
    it(`ABORTS on ${name}`, () => {
      let escaped = "untouched";
      expect(() => {
        escaped = runCheck({ html: bad, previous: null, config: null, now: NOW, today: TODAY });
      }).toThrow(/no fixtures/i);
      // Nothing partial escapes: the caller cannot accidentally persist half a run.
      expect(escaped).toBe("untouched");
    });
  }

  it("aborts even when a previous snapshot and config already exist", () => {
    expect(() =>
      runCheck({ html: "<html>blocked</html>", previous: first.snapshot, config: first.config, now: NOW, today: TODAY }),
    ).toThrow(/no fixtures/i);
  });

  it("names the response, not a generic failure, so the log is diagnosable", () => {
    expect(() => runCheck({ html: "", previous: null, config: null, now: NOW, today: TODAY }))
      .toThrow(/aborting/i);
  });
});

describe("runCheck change direction", () => {
  // If prev/next were ever swapped every change would read backwards: this pins it.
  it("reports a genuinely new fixture as added, never as cancelled", () => {
    const dropped = first.snapshot.fixtures[3];
    const previous = prevWith((fs) => fs.filter((f) => f.fid !== dropped.fid));
    const out = runCheck({ html, previous, config: first.config, now: NOW, today: TODAY });
    expect(out.changes).toHaveLength(1);
    expect(out.changes[0].type).toBe("added");
    expect(out.changes[0].fid).toBe(dropped.fid);
  });

  it("reports a fixture that has left the list as cancelled, never as added", () => {
    const ghost = { ...first.snapshot.fixtures[0], fid: "9999999", date: "2026-12-01" };
    const previous = prevWith((fs) => [...fs, ghost]);
    const out = runCheck({ html, previous, config: first.config, now: NOW, today: TODAY });
    expect(out.changes).toHaveLength(1);
    expect(out.changes[0].type).toBe("cancelled");
    expect(out.changes[0].fid).toBe("9999999");
  });

  it("reads a move forwards: from the old kick-off to the new one", () => {
    const previous = prevWith((fs) => fs.map((f, i) => (i === 0 ? { ...f, time: "09:00" } : f)));
    const out = runCheck({ html, previous, config: first.config, now: NOW, today: TODAY });
    expect(out.changes[0].from).toEqual({ date: first.snapshot.fixtures[0].date, time: "09:00" });
    expect(out.changes[0].to).toEqual({
      date: first.snapshot.fixtures[0].date,
      time: first.snapshot.fixtures[0].time,
    });
  });

  it("reads a venue change forwards", () => {
    const previous = prevWith((fs) => fs.map((f, i) => (i === 0 ? { ...f, venue: "Nowhere" } : f)));
    const out = runCheck({ html, previous, config: first.config, now: NOW, today: TODAY });
    expect(out.changes[0].from).toBe("Nowhere");
    expect(out.changes[0].to).toBe(first.snapshot.fixtures[0].venue);
  });
});

describe("runCheck squad labels", () => {
  // deriveLabels only shows the A/B letter when the club runs more than one side at that
  // age and gender, so labels MUST be resolved over the whole new snapshot. Resolving
  // over just the changed fixtures would rename this squad to "U14 Boys".
  it("labels the U14B side from the full snapshot when its fixture is the only change", () => {
    const b = first.snapshot.fixtures.find((f) => f.teamId === "254061");
    expect(b).toBeDefined();
    // Labels cleared, so the report has to derive them rather than read them back.
    const unlabelled = {
      version: first.config.version,
      teams: Object.fromEntries(
        Object.entries(first.config.teams).map(([id, t]) => [id, { ...t, label: null }]),
      ),
    };
    const previous = prevWith((fs) => fs.map((f) => (f.fid === b.fid ? { ...f, time: "09:00" } : f)));
    const out = runCheck({ html, previous, config: unlabelled, now: NOW, today: TODAY });
    expect(out.changes).toHaveLength(1);
    expect(out.changes[0].teamId).toBe("254061");
    expect(out.report.text).toContain("U14B Boys");
    expect(out.report.text).not.toContain("U14 Boys ");
  });

  it("lists exactly the squads whose config label is null as unknown", () => {
    const nulls = Object.entries(first.config.teams)
      .filter(([, t]) => t.label === null)
      .map(([id]) => id);
    expect(nulls.length).toBeGreaterThan(0);
    expect([...first.unknown].sort()).toEqual([...nulls].sort());
  });

  it("computes unknown from the new fixtures, not from the previous snapshot", () => {
    const gone = first.unknown[0];
    const previous = prevWith((fs) => fs.filter((f) => f.teamId !== gone));
    const out = runCheck({ html, previous, config: first.config, now: NOW, today: TODAY });
    expect([...out.unknown].sort()).toEqual([...first.unknown].sort());
  });

  it("mentions the unlabelled squads in the alert email", () => {
    const previous = prevWith((fs) => fs.map((f, i) => (i === 0 ? { ...f, venue: "Nowhere" } : f)));
    const out = runCheck({ html, previous, config: first.config, now: NOW, today: TODAY, siteUrl: "https://x.test" });
    for (const id of out.unknown) expect(out.report.text).toContain(id);
    expect(out.report.text).toContain("https://x.test");
  });
});

describe("runCheck config seeding", () => {
  it("adds every missing squad to a config that does not know about them", () => {
    const out = runCheck({ html, previous: null, config: { version: 1, teams: {} }, now: NOW, today: TODAY });
    expect(Object.keys(out.config.teams)).toHaveLength(TEAM_COUNT);
  });

  it("keeps a label the owner already set", () => {
    const config = { version: 1, teams: { "235380": { label: "The A team", color: "#123456" } } };
    const out = runCheck({ html, previous: null, config, now: NOW, today: TODAY });
    expect(out.config.teams["235380"].label).toBe("The A team");
    expect(Object.keys(out.config.teams)).toHaveLength(TEAM_COUNT);
  });

  // The cron runs every morning: config churn means a pointless commit every day.
  it("is idempotent on a second run - byte-identical config, no changes", () => {
    const second = runCheck({ html, previous: first.snapshot, config: first.config, now: NOW, today: TODAY });
    expect(JSON.stringify(second.config)).toBe(JSON.stringify(first.config));
    expect(second.changes).toEqual([]);
    expect(second.snapshot).toEqual(first.snapshot);
    const third = runCheck({ html, previous: second.snapshot, config: second.config, now: NOW, today: TODAY });
    expect(JSON.stringify(third.config)).toBe(JSON.stringify(second.config));
  });
});

describe("runCheck resilience", () => {
  // One bad block costs that block and nothing else.
  const corrupted = html.replace('data-fid="6951014"', 'data-fid=""');

  it("surfaces parse errors without failing the run", () => {
    expect(corrupted).not.toBe(html);
    const out = runCheck({ html: corrupted, previous: null, config: null, now: NOW, today: TODAY });
    expect(out.snapshot.fixtures).toHaveLength(FIXTURE_COUNT - 1);
    expect(out.errors).toHaveLength(1);
    expect(out.errors[0]).toMatch(/fid/i);
  });

  it("reports no errors on the clean capture", () => {
    expect(first.errors).toEqual([]);
  });

  for (const [name, previous] of [
    ["null", null],
    ["undefined", undefined],
    ["an empty object", {}],
    ["a snapshot whose fixtures are not a list", { version: 1, fixtures: "nope" }],
    ["a snapshot with no fixtures key", { version: 1, fetchedAt: NOW }],
  ]) {
    it(`treats a previous snapshot that is ${name} as a first run`, () => {
      const out = runCheck({ html, previous, config: first.config, now: NOW, today: TODAY });
      expect(out.firstRun).toBe(true);
      expect(out.changes).toEqual([]);
      expect(out.report).toBeNull();
      expect(out.snapshot.fixtures).toHaveLength(FIXTURE_COUNT);
    });
  }
});

describe("runCheck on a busy morning", () => {
  // A realistic mix: a kick-off moved, a venue switched, a fixture added and one cancelled.
  let out;
  beforeAll(() => {
    const moved = first.snapshot.fixtures[0];
    const venue = first.snapshot.fixtures[5];
    const added = first.snapshot.fixtures[9];
    const ghost = { ...first.snapshot.fixtures[2], fid: "8888888", date: "2026-11-11", time: "10:30" };

    const previous = prevWith((fs) => [
      ...fs
        .filter((f) => f.fid !== added.fid)
        .map((f) => {
          if (f.fid === moved.fid) return { ...f, time: "09:00" };
          if (f.fid === venue.fid) return { ...f, venue: "Old Field" };
          return f;
        }),
      ghost,
    ]);

    out = runCheck({ html, previous, config: first.config, now: NOW, today: TODAY, history: [] });
  });

  it("reports every change once, most disruptive first", () => {
    expect(out.changes).toHaveLength(4);
    expect(out.changes.map((c) => c.type)).toEqual(["cancelled", "moved", "venue", "added"]);
  });

  it("summarises them in the subject line", () => {
    expect(out.report.subject).toBe(
      "Craughwell fixtures: 4 changes (1 cancelled, 1 moved, 1 venue change, 1 new)",
    );
  });

  it("records exactly this run's changes at the head of the history", () => {
    expect(out.history).toHaveLength(1);
    expect(out.history[0].checkedAt).toBe(NOW);
    expect(out.history[0].changes).toEqual(out.changes);
  });

  it("still writes the full new snapshot", () => {
    expect(out.snapshot.fixtures).toHaveLength(FIXTURE_COUNT);
    expect(out.snapshot.fetchedAt).toBe(NOW);
  });
});

// The likelier failure: the league tweaks their markup, MOST blocks stop matching, and the
// owner is emailed dozens of cancellations that never happened.
describe("runCheck aborts when the fixture count collapses", () => {
  // Every fid in the capture is unique, so blanking one kills exactly that block.
  const fids = [...html.matchAll(/data-fid="(\d+)"/g)].map((m) => m[1]);

  // The real capture with all but the first `n` fixture blocks broken.
  const keepingOnly = (n) =>
    fids.slice(n).reduce((acc, fid) => acc.replace(`data-fid="${fid}"`, 'data-fid=""'), html);

  const run = (opts) =>
    runCheck({ previous: first.snapshot, config: first.config, now: NOW, today: TODAY, ...opts });

  it("blanks exactly as many blocks as asked, so these tests mean what they say", () => {
    expect(fids).toHaveLength(FIXTURE_COUNT);
    const out = runCheck({ html: keepingOnly(30), previous: null, config: null, now: NOW, today: TODAY });
    expect(out.snapshot.fixtures).toHaveLength(30);
    expect(out.errors).toHaveLength(FIXTURE_COUNT - 30);
  });

  it("ABORTS when 49 fixtures collapse to 24", () => {
    let escaped = "untouched";
    expect(() => {
      escaped = run({ html: keepingOnly(24) });
    }).toThrow(/collapsed/i);
    expect(escaped).toBe("untouched");
  });

  it("names both counts so the log says what happened", () => {
    expect(() => run({ html: keepingOnly(24) })).toThrow(/from 49 to 24/);
  });

  it("tells the operator how to force a genuine collapse through", () => {
    expect(() => run({ html: keepingOnly(24) })).toThrow(/allowShrink/);
  });

  // The threshold is deliberate, not incidental: 25 of 49 is above half and gets through.
  it("allows a shrink to just above the limit", () => {
    const out = run({ html: keepingOnly(25) });
    expect(out.snapshot.fixtures).toHaveLength(25);
  });

  it("pins the limit at half", () => {
    expect(SHRINK_LIMIT).toBe(0.5);
    expect(25).toBeGreaterThanOrEqual(FIXTURE_COUNT * SHRINK_LIMIT);
    expect(24).toBeLessThan(FIXTURE_COUNT * SHRINK_LIMIT);
  });

  it("lets a collapse through with allowShrink, and writes the smaller snapshot", () => {
    const out = run({ html: keepingOnly(24), allowShrink: true });
    expect(out.snapshot.fixtures).toHaveLength(24);
    expect(out.changes.length).toBeGreaterThan(0);
    expect(out.changes.every((c) => c.type === "cancelled")).toBe(true);
  });

  it("still aborts on zero fixtures even with allowShrink - the more specific rule wins", () => {
    expect(() => run({ html: "<html>blocked</html>", allowShrink: true })).toThrow(/no fixtures/i);
  });

  it("uses the zero-fixtures message, not the collapse one, for a total failure", () => {
    expect(() => run({ html: "<html>blocked</html>" })).toThrow(/no fixtures/i);
    expect(() => run({ html: "<html>blocked</html>" })).not.toThrow(/collapsed/i);
  });

  it("does not abort on a first run - there is no baseline to shrink from", () => {
    const out = runCheck({ html: keepingOnly(3), previous: null, config: null, now: NOW, today: TODAY });
    expect(out.snapshot.fixtures).toHaveLength(3);
    expect(out.firstRun).toBe(true);
  });

  it("does not abort against a previous snapshot that holds no fixtures", () => {
    const previous = { version: 1, fetchedAt: "2026-08-24T06:00:00Z", fixtures: [] };
    const out = runCheck({ html: keepingOnly(3), previous, config: first.config, now: NOW, today: TODAY });
    expect(out.snapshot.fixtures).toHaveLength(3);
  });

  it("does not abort on the ordinary shrink of a season being played out", () => {
    const out = run({ html: keepingOnly(FIXTURE_COUNT - 4) });
    expect(out.snapshot.fixtures).toHaveLength(FIXTURE_COUNT - 4);
    expect(out.changes).toHaveLength(4);
    expect(out.changes.every((c) => c.type === "cancelled")).toBe(true);
  });

  // The actual scenario: a markup change most blocks no longer match.
  it("ABORTS rather than emailing mass cancellations when the markup changes under it", () => {
    const broken = keepingOnly(6);
    // Sanity: without the guard this run would report 43 cancellations.
    const wouldBe = runCheck({ html: broken, previous: null, config: null, now: NOW, today: TODAY });
    expect(wouldBe.snapshot.fixtures).toHaveLength(6);
    expect(() => run({ html: broken })).toThrow(/collapsed from 49 to 6/);
  });

  it("leaves the previous snapshot and config untouched when it aborts", () => {
    const snapshotBefore = JSON.stringify(first.snapshot);
    const configBefore = JSON.stringify(first.config);
    expect(() => run({ html: keepingOnly(2) })).toThrow(/collapsed/i);
    expect(JSON.stringify(first.snapshot)).toBe(snapshotBefore);
    expect(JSON.stringify(first.config)).toBe(configBefore);
  });

  it("agrees with the first-run check about what counts as a baseline", () => {
    // A corrupted snapshot must be a first run for BOTH the diff and the shrink guard.
    // The long string is the one with teeth: a `?.length` read gives a baseline of 100,
    // so 49 fixtures looks like a collapse and the shrink guard aborts - while the diff
    // path calls the very same snapshot a first run.
    for (const previous of [{ fixtures: "nope" }, { fixtures: 49 }, {}, { fixtures: "x".repeat(100) }]) {
      const out = runCheck({ html, previous, config: null, now: NOW, today: TODAY });
      expect(out.firstRun).toBe(true);
      expect(out.snapshot.fixtures).toHaveLength(FIXTURE_COUNT);
    }
  });
});
